version: "3.7"

services:
  nginx:
    build: ".docker/local/nginx"
    container_name: cart-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: ".docker/local/php"
    container_name: cart-app
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
      - minio
    extra_hosts:
      - "www.cart-memo.test:127.0.0.1"
      - "admin.cart-memo.test:127.0.0.1"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: cart
      MYSQL_USER: cart
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    container_name: cart-mysql

  redis:
    image: redis:6.0.5
    container_name: cart-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: cart-minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server /export

  bucket:
    container_name: cart-bucket
    image: minio/mc
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        until (mc config host add minio http://minio:9000 access_key secret_key) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/test
        mc policy set public minio/test
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    depends_on:
      - minio

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
